// @generated by protoc-gen-es v2.2.2 with parameter "target=js,js_import_style=module,json_types=true"
// @generated from file main/v1/auth.proto (package main.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file main/v1/auth.proto.
 */
export const file_main_v1_auth = /*@__PURE__*/
  fileDesc("ChJtYWluL3YxL2F1dGgucHJvdG8SB21haW4udjEiMAoNU2lnblVwUmVxdWVzdBINCgVlbWFpbBgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSIwCg5TaWduVXBSZXNwb25zZRINCgV0b2tlbhgBIAEoCRIPCgdtZXNzYWdlGAIgASgJIi8KDExvZ2luUmVxdWVzdBINCgVlbWFpbBgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSIvCg1Mb2dpblJlc3BvbnNlEg0KBXRva2VuGAEgASgJEg8KB21lc3NhZ2UYAiABKAlCVQoLY29tLm1haW4udjFCCUF1dGhQcm90b1ABogIDTVhYqgIHTWFpbi5WMcoCB01haW5cVjHiAhNNYWluXFYxXEdQQk1ldGFkYXRh6gIITWFpbjo6VjFiBnByb3RvMw");

/**
 * Describes the message main.v1.SignUpRequest.
 * Use `create(SignUpRequestSchema)` to create a new message.
 */
export const SignUpRequestSchema = /*@__PURE__*/
  messageDesc(file_main_v1_auth, 0);

/**
 * Describes the message main.v1.SignUpResponse.
 * Use `create(SignUpResponseSchema)` to create a new message.
 */
export const SignUpResponseSchema = /*@__PURE__*/
  messageDesc(file_main_v1_auth, 1);

/**
 * Describes the message main.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema = /*@__PURE__*/
  messageDesc(file_main_v1_auth, 2);

/**
 * Describes the message main.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema = /*@__PURE__*/
  messageDesc(file_main_v1_auth, 3);

