// @generated by protoc-gen-es v2.2.2 with parameter "target=js,js_import_style=module,json_types=true"
// @generated from file main/v1/ping.proto (package main.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file main/v1/ping.proto.
 */
export const file_main_v1_ping = /*@__PURE__*/
  fileDesc("ChJtYWluL3YxL3BpbmcucHJvdG8SB21haW4udjEiDQoLUGluZ1JlcXVlc3QiHAoMUGluZ1Jlc3BvbnNlEgwKBGh0bWwYASABKAlCVQoLY29tLm1haW4udjFCCVBpbmdQcm90b1ABogIDTVhYqgIHTWFpbi5WMcoCB01haW5cVjHiAhNNYWluXFYxXEdQQk1ldGFkYXRh6gIITWFpbjo6VjFiBnByb3RvMw");

/**
 * Describes the message main.v1.PingRequest.
 * Use `create(PingRequestSchema)` to create a new message.
 */
export const PingRequestSchema = /*@__PURE__*/
  messageDesc(file_main_v1_ping, 0);

/**
 * Describes the message main.v1.PingResponse.
 * Use `create(PingResponseSchema)` to create a new message.
 */
export const PingResponseSchema = /*@__PURE__*/
  messageDesc(file_main_v1_ping, 1);

