// @generated by protoc-gen-es v2.2.2
// @generated from file main/v1/ping.proto (package main.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file main/v1/ping.proto.
 */
export declare const file_main_v1_ping: GenFile;

/**
 * @generated from message main.v1.PingRequest
 */
export declare type PingRequest = Message<"main.v1.PingRequest"> & {
};

/**
 * Describes the message main.v1.PingRequest.
 * Use `create(PingRequestSchema)` to create a new message.
 */
export declare const PingRequestSchema: GenMessage<PingRequest>;

/**
 * @generated from message main.v1.PingResponse
 */
export declare type PingResponse = Message<"main.v1.PingResponse"> & {
  /**
   * @generated from field: string html = 1;
   */
  html: string;
};

/**
 * Describes the message main.v1.PingResponse.
 * Use `create(PingResponseSchema)` to create a new message.
 */
export declare const PingResponseSchema: GenMessage<PingResponse>;

