// @generated by protoc-gen-es v2.2.2 with parameter "target=js,js_import_style=module,json_types=true"
// @generated from file main/v1/queue_up.proto (package main.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file main/v1/queue_up.proto.
 */
export const file_main_v1_queue_up = /*@__PURE__*/
  fileDesc("ChZtYWluL3YxL3F1ZXVlX3VwLnByb3RvEgdtYWluLnYxIhAKDlF1ZXVlVXBSZXF1ZXN0IiEKD1F1ZXVlVXBSZXNwb25zZRIOCgZzdGF0dXMYASABKAlCWAoLY29tLm1haW4udjFCDFF1ZXVlVXBQcm90b1ABogIDTVhYqgIHTWFpbi5WMcoCB01haW5cVjHiAhNNYWluXFYxXEdQQk1ldGFkYXRh6gIITWFpbjo6VjFiBnByb3RvMw");

/**
 * Describes the message main.v1.QueueUpRequest.
 * Use `create(QueueUpRequestSchema)` to create a new message.
 */
export const QueueUpRequestSchema = /*@__PURE__*/
  messageDesc(file_main_v1_queue_up, 0);

/**
 * Describes the message main.v1.QueueUpResponse.
 * Use `create(QueueUpResponseSchema)` to create a new message.
 */
export const QueueUpResponseSchema = /*@__PURE__*/
  messageDesc(file_main_v1_queue_up, 1);

