// @generated by protoc-gen-es v2.2.2
// @generated from file main/v1/queue_up.proto (package main.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file main/v1/queue_up.proto.
 */
export declare const file_main_v1_queue_up: GenFile;

/**
 * @generated from message main.v1.QueueUpRequest
 */
export declare type QueueUpRequest = Message<"main.v1.QueueUpRequest"> & {
};

/**
 * Describes the message main.v1.QueueUpRequest.
 * Use `create(QueueUpRequestSchema)` to create a new message.
 */
export declare const QueueUpRequestSchema: GenMessage<QueueUpRequest>;

/**
 * @generated from message main.v1.QueueUpResponse
 */
export declare type QueueUpResponse = Message<"main.v1.QueueUpResponse"> & {
  /**
   * @generated from field: string status = 1;
   */
  status: string;
};

/**
 * Describes the message main.v1.QueueUpResponse.
 * Use `create(QueueUpResponseSchema)` to create a new message.
 */
export declare const QueueUpResponseSchema: GenMessage<QueueUpResponse>;

