// @generated by protoc-gen-es v2.2.2 with parameter "target=js,js_import_style=module,json_types=true"
// @generated from file main/v1/server.proto (package main.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_main_v1_ping } from "./ping_pb";
import { file_main_v1_queue_up } from "./queue_up_pb";
import { file_google_api_annotations } from "../../google/api/annotations_pb";

/**
 * Describes the file main/v1/server.proto.
 */
export const file_main_v1_server = /*@__PURE__*/
  fileDesc("ChRtYWluL3YxL3NlcnZlci5wcm90bxIHbWFpbi52MTKhAQoLTWFpblNlcnZpY2USRAoEUGluZxIULm1haW4udjEuUGluZ1JlcXVlc3QaFS5tYWluLnYxLlBpbmdSZXNwb25zZSIPgtPkkwIJEgcvcGluZ21lEkwKB1F1ZXVlVXASFy5tYWluLnYxLlF1ZXVlVXBSZXF1ZXN0GhgubWFpbi52MS5RdWV1ZVVwUmVzcG9uc2UiDoLT5JMCCBIGL3F1ZXVlQlcKC2NvbS5tYWluLnYxQgtTZXJ2ZXJQcm90b1ABogIDTVhYqgIHTWFpbi5WMcoCB01haW5cVjHiAhNNYWluXFYxXEdQQk1ldGFkYXRh6gIITWFpbjo6VjFiBnByb3RvMw", [file_main_v1_ping, file_main_v1_queue_up, file_google_api_annotations]);

/**
 * @generated from service main.v1.MainService
 */
export const MainService = /*@__PURE__*/
  serviceDesc(file_main_v1_server, 0);

