// @generated by protoc-gen-es v2.2.2
// @generated from file main/v1/server.proto (package main.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import type { PingRequestSchema, PingResponseSchema } from "./ping_pb";
import type { QueueUpRequestSchema, QueueUpResponseSchema } from "./queue_up_pb";

/**
 * Describes the file main/v1/server.proto.
 */
export declare const file_main_v1_server: GenFile;

/**
 * @generated from service main.v1.MainService
 */
export declare const MainService: GenService<{
  /**
   * @generated from rpc main.v1.MainService.Ping
   */
  ping: {
    methodKind: "unary";
    input: typeof PingRequestSchema;
    output: typeof PingResponseSchema;
  },
  /**
   * @generated from rpc main.v1.MainService.QueueUp
   */
  queueUp: {
    methodKind: "unary";
    input: typeof QueueUpRequestSchema;
    output: typeof QueueUpResponseSchema;
  },
}>;

